on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: ENV clone
        run: |
         echo "Creating .env file..."
         touch .env
         echo API_KEY=${{ secrets.API_KEY }} >> .env
         echo API_SECRET=${{ secrets.API_SECRET }} >> .env
         echo "env file is created."
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
